In [1]:
import numpy as np
import networkx as nx
import pandas as pd
import pickle

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
od_flow = pd.read_csv('mean_df_20210224_20210424.csv')
#value is the od matrix
value = od_flow.values[0:-1,1:-1]
value =np.array([np.array([float(i) for i in j ])for j in value])
actualcommunter_scaler = 4753898/np.sum(value)
value = value*actualcommunter_scaler
value = 1/value

/var/folders/b3/kkdtnh4d4gjgrk45d_yrf4100000gn/T/ipykernel_39216/460112638.py:7: RuntimeWarning: divide by zero encountered in divide
  value = 1/value


In [3]:
G = nx.from_numpy_matrix(value)

In [4]:
v = nx.betweenness_centrality(G, weight= 'weight')

In [5]:
weights_bc = list(v.values())

In [6]:
weights_bc

[0.09000000000000001,
 0.0,
 0.0,
 0.17333333333333334,
 0.0,
 0.04,
 0.10666666666666667,
 0.08,
 0.0,
 0.4066666666666667,
 0.32333333333333336,
 0.0,
 0.0,
 0.5866666666666667,
 0.08,
 0.0,
 0.0,
 0.0,
 0.16666666666666669,
 0.14666666666666667,
 0.0,
 0.0,
 0.0,
 0.0,
 0.23,
 0.0]

In [7]:
with open('weights_bc.pkl', 'wb') as file:
    pickle.dump(weights_bc, file)

In [8]:
od_flow = pd.read_csv('mean_df_20210224_20210424.csv')
#value is the od matrix
value = od_flow.values[0:-1,1:-1]
value =np.array([np.array([float(i) for i in j ])for j in value])
actualcommunter_scaler = 4753898/np.sum(value)
value = value*actualcommunter_scaler

In [9]:
from numpy import linalg as LA
eigenvalues, eigenvectors = LA.eig(value)

In [10]:
weights_eig = 1/(np.argsort(eigenvalues)+1)

In [11]:
with open('weights_eig.pkl', 'wb') as file:
    pickle.dump(weights_eig, file)

In [12]:
c = np.genfromtxt ('cases.csv', delimiter=",")


In [24]:
np.sum(c[:120],axis=0)

array([3167.        , 5234.        , 2370.        , 6171.        ,
       9494.        , 2141.        , 5041.        , 2439.        ,
       1506.51507936, 5140.        , 7329.        , 5265.        ,
       4148.        , 3325.        , 5024.        , 5415.        ,
       2469.        , 5041.        , 3599.        , 4042.        ,
       8205.        , 3786.        , 2327.        , 4279.        ,
       5283.23474368, 2293.        ])

In [14]:
weights_case = np.sum(c[:120],axis=0)/np.sum(c[:120])

In [15]:
weights_case

array([0.02765124, 0.04569832, 0.02069259, 0.05387932, 0.0828926 ,
       0.01869318, 0.04401323, 0.02129503, 0.01315346, 0.0448776 ,
       0.06398987, 0.04596898, 0.0362164 , 0.02903074, 0.0438648 ,
       0.04727864, 0.02155696, 0.04401323, 0.03142305, 0.03529091,
       0.07163827, 0.03305576, 0.02031716, 0.03736017, 0.04612819,
       0.0200203 ])

In [16]:
with open('weights_case.pkl', 'wb') as file:
    pickle.dump(weights_case, file)

In [17]:
totalpop = np.array([420697,443569,344450,526877,899111,339399,419797,308499,140361,547523,354750,479505,287613,666399,278815,193899,166374,379199,356465,195082,407864,321720,201739,411617,469439,465691])


In [18]:
case_rate = np.sum(c[:120],axis=0)/totalpop

In [23]:
case_rate*1000

array([ 7.52798332, 11.79974254,  6.88053418, 11.71241106, 10.55931915,
        6.30820951, 12.00818491,  7.90602239, 10.73314581,  9.38773348,
       20.65961945, 10.9800732 , 14.42215755,  4.98950329, 18.01911662,
       27.9269104 , 14.84005914, 13.29381143, 10.0963629 , 20.71949232,
       20.11699978, 11.76799702, 11.53470573, 10.39558619, 11.25435838,
        4.92386583])

In [25]:
weights_prv = case_rate*1000

In [26]:
with open('weights_prv.pkl', 'wb') as file:
    pickle.dump(weights_prv, file)